### ISSUE TITLE
Improve repository description and add tags

### ISSUE THREAD

**Issue by iby** [njdehoog/Witness#6]
Thanks for the project! While this is one of the most up to date and neatest projects it seems a little tricky to find. Consider changing description to include `file system events watch swift` and adding tags. More will find it. More will use it. More will contribute.

![2018-06-11 12 02 48](https://user-images.githubusercontent.com/1086845/41219588-d0ba9ffe-6d6f-11e8-8d65-0b99c3c9c33b.gif)

**Comment by njdehoog** [comment]
Thanks for the advice! I updated the description and added some topics.
